QUES_VAL = {
    "who or what did .* oppose?": -1.0, 
    "who or what did .* work with?": 0.9, 
    "who or what did .* support?": 1.0, 
    "who or what did .* threaten?": -1.0, 
    "who or what was at .*?": 0.4,
    "who worked at .*?": 0.7,
    "who was at .*?": 0.4,
    "who did .* oppose?": -1.0,
    "who participated .*?": 0.8,
    "who wrote .*?": 1.0,
    "where did .* work?": 0.7,
    "where was .* located?": 0.4,
    "where or whom from did .* come from?": 0.4,
    "where or whom to did .* go?": 0.4,
    "what did .* do?": 0.8,
    "what did .* enforce?": 1.0,
    "what happened .*?": 0.0,
    "what happened at .*?": 0.3,
    "what happened in or at .*?": 0.3,
    "what did .* accomplish?": 0.8,
    "what was .* accomplish?": 0.8,
    "what was .* spent on?": 0.8,
    "what was .* used for?": 0.8
}