QUES_VAL = {
    "who or what did .* oppose?": -1.0, 
    "who or what did .* work with?": 0.1, 
    "who or what did .* support?": 1.0, 
    "who or what did .* threaten?": -1.0, 
    'Who or what did .* save?': 1.0,
    "who or what was at .*?": 0.1,
    "who worked at .*?": 0.25,
    "who was at .*?": 0.1,
    "who did .* oppose?": -1.0,
    "who participated .*?": 1.0,
    "who wrote .*?": 1.0,
    "where did .* work?": 0.25,
    "where was .* located?": 0.1,
    "where or whom from did .* come from?": 0.1,
    "where or whom to did .* go?": 0.1,
    "what did .* do?": 1.0,
    "what did .* enforce?": 1.0,
    #"what happened .*?": 0.0,
    #"what happened at .*?": 0.3,
    #"what happened in or at .*?": 0.3,
    "what did .* accomplish?": 1.0,
    "what was .* accomplish?": 1.0,
    "what was .* spent on?": 0.1,
    "what was .* used for?": 0.1
}

QUES_VAL_2 = {
    'Who or what did .* support?': 1.0,
    'Who or what did .* oppose?': -1.0,
    'Who or what did .* threaten?': -1.5,
    'Who or what did .* work with?': 1,
    'Who or what did .* save?': 1.5,
    'Who or what was at .*?': 0.5,
    'Who was at .*?': 0.5,
    'Who worked at .*?': 0.5,
    'Who did .* oppose?': -1,
    'Who wrote .*?': 1.0,
    'Who participated .*?': 0.5,
    #'Who participated at .*?': 0.5,
    'Where was .* located?': 0,
    'Where or whom to did the .* go?': 1.0,
    'Where or whom from did the .* come from?': 1.0,
    'Where did .* work?': 0.5,
    'What did .* do?': 0,
    'What did .* enforce?': 1.0,
    'What was .* used for?': 0.5,
    'What happened .*?': 0.0,
    #'What happened at .*?': 0.0,
    'What was .* spent on?': 1.0,
    'What did the .* accomplish?': 1.0,
    'What was .* accomplish?': 1.0,
}
